sudo: required

language: erlang

otp_release:
- 19.1


before_install:
- add-apt-repository ppa:pitti/systemd -y
- apt-get -qq update
- apt-get install systemd libpam-systemd systemd-ui -y 

script:
- make all 
- make test
