sudo: required

language: erlang

otp_release:
- 18.0

services:
- docker

before_install:
- kerl list installations
- docker build -t build_ubuntu ubuntu_18_3/Dockerfile
- docker images

script:
- docker run -v $TRAVIS_BUILD_DIR:/home/sd/ build_ubuntu /bin/sh -c "cd /home/sd/; make all; make test"
