FROM ubuntu:16.04

RUN apt-get -y update 

RUN  apt-get install -y  \
  gcc \
  make \
  git  \
  wget \
  erlang=1:18.3-dfsg-1ubuntu3.1 \
  build-essential \
	devscripts \
	fakeroot \
    debhelper \
    erlang-dev \
    libsystemd-dev\
    erlang-eunit \
    rebar




